export const perfumes = [
  {
    id: '1',
    name: "RASASI Eau De Parfum For Men Long Lasting Liquid Perfume Luxury Perfume Premium Perfume For Men (Unscented , 50 ml,Fattan)",
    price: '1547',
    originalPrice: '1547',
    currentPrice: '',
    priceDate: '2024-01-15',
    image: 'https://m.media-amazon.com/images/I/51XjlOT72mL._SX522_.jpg',
    buyLink: "https://amzn.in/d/1SIyVwX",
    brand: "RASASI",
    volume: "50ml",
    description: "Long lasting luxury perfume for men with premium fragrance notes."
  },
  {
    id: '2',
    name: "BENTLEY Men Transparent Silverlake Eau de Parfum",
    price: "6225",
    originalPrice: "6225",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/51mGrFw6jdL._SX522_.jpg",
    buyLink: "https://amzn.in/d/jhQmbrL",
    brand: "BENTLEY",
    volume: "100ml",
    description: "Transparent Silverlake fragrance with sophisticated masculine notes."
  },
  {
    id: '3',
    name: "Al Haramain Amber Oud Eau De Parfum Spray | Arabian Perfume for Men & Women",
    price: "6999",
    originalPrice: "6999",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/51Dkv7sgXfL._SX522_.jpg",
    buyLink: "https://amzn.in/d/8PoVBb9",
    brand: "Al Haramain",
    volume: "60ml",
    description: "Authentic Arabian amber oud fragrance for both men and women."
  },
  {
    id: '4',
    name: "Rue Broca Theoreme Pour Homme Eau De Parfum 90ml For Him | Monsoon + All Weather",
    price: "1930",
    originalPrice: "1930",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/31sxEVEJPVL._SX522_.jpg",
    buyLink: "https://amzn.in/d/fwrtYvb",
    brand: "Rue Broca",
    volume: "90ml",
    description: "All weather fragrance perfect for monsoon and daily wear."
  },
  {
    id: '5',
    name: "Lattafa Najdia Intense for Men Eau De Parfum Spray",
    price: "2125",
    originalPrice: "2125",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/81v87Ee+V9L._SX522_.jpg",
    buyLink: "https://amzn.in/d/jeziw0F",
    brand: "Lattafa",
    volume: "100ml",
    description: "Intense masculine fragrance with long-lasting oriental notes."
  },
  {
    id: '6',
    name: "Rasasi Hawas Eau De Parfum For Men",
    price: "3349",
    originalPrice: "3349",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/61AaKL1AhVL._SX522_.jpg",
    buyLink: "https://amzn.in/d/bzKSXmN",
    brand: "Rasasi",
    volume: "100ml",
    description: "Fresh aquatic fragrance with citrus and woody base notes."
  },
  {
    id: '7',
    name: "Creed Aventus Perfume Spray for Men's",
    price: "38349",
    originalPrice: "38349",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/519sP9WD+rL._SX522_.jpg",
    buyLink: "https://amzn.in/d/eO6bEug",
    brand: "Creed",
    volume: "100ml",
    description: "Luxury premium fragrance with pineapple, birch, and musk notes."
  },
  {
    id: '8',
    name: "The Man Company Fresh Black Edt Perfume For Men",
    price: "549",
    originalPrice: "549",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/61P34NndpLL._SX522_.jpg",
    buyLink: "https://amzn.in/d/2OMsTjr",
    brand: "The Man Company",
    volume: "100ml",
    description: "Fresh black fragrance with citrus and woody undertones."
  },
  {
    id: '9',
    name: "The Man Company Fire EDP - 50ml | Perfume Spray For Men's",
    price: "374",
    originalPrice: "374",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/6196QoOINUL._SX522_.jpg",
    buyLink: "https://amzn.in/d/4kO3Kc8",
    brand: "The Man Company",
    volume: "50ml",
    description: "Fiery masculine fragrance with spicy and warm notes."
  },
  {
    id: '10',
    name: "Wild Stone Edge Eau De Parfum for Men",
    price: "314",
    originalPrice: "314",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/61BXRNekoEL._SX522_.jpg",
    buyLink: "https://amzn.in/d/dtDv9A9",
    brand: "Wild Stone",
    volume: "100ml",
    description: "Long lasting edge fragrance with contemporary masculine appeal."
  },
  {
    id: '11',
    name: "Skinn By Titan Raw Long Lasting EDP for Men | Perfume Spray",
    price: "2795",
    originalPrice: "2795",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/61yZJiJvgoL._SX522_.jpg",
    buyLink: "https://amzn.in/d/5z1ptHv",
    brand: "Skinn By Titan",
    volume: "100ml",
    description: "Raw masculine fragrance with intense and long-lasting formula."
  },
  {
    id: '12',
    name: "Afnan Supremacy Not Only Intense Eau De Parfum For Men",
    price: "5899",
    originalPrice: "5899",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://m.media-amazon.com/images/I/61gWYHLpHsL._SX522_.jpg",
    buyLink: "https://www.fridaycharm.com/products/afnan-supremacy-not-only-intense-edp-100ml?variant=45142233809142",
    brand: "Afnan",
    volume: "100ml",
    description: "Supremacy intense fragrance with powerful and sophisticated notes."
  },
  {
    id: '13',
    name: "Rasasi Hawas Ice Eau de Parfum for Men",
    price: "2699",
    originalPrice: "2699",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.perfumenetwork.in/cdn/shop/files/HawasIce.png?v=1735282503",
    buyLink: "https://elixbloom.com/product/rasasi-hawas-him-100ml-edp-men/, https://www.perfumenetwork.in/products/rasasi-hawas-ice-eau-de-parfum-for-men",
    brand: "Rasasi",
    volume: "100ml",
    description: "Fresh icy variant of the popular Hawas fragrance with aquatic notes."
  },
  {
    id: '14',
    name: "Armaf Club De Nuit Intense Man Pure Parfum",
    price: "3949",
    originalPrice: "3949",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://elixbloom.com/wp-content/uploads/2025/04/EDP1-copy.webp",
    buyLink: "https://elixbloom.com/product/armaf-club-de-nuit-intense-man-pure-parfum-150ml-men/, https://armafperfume.com/products/armaf-club-de-nuit-intense-pure-parfum-for-man-150ml",
    brand: "Armaf",
    volume: "150ml",
    description: "Pure parfum concentration with intense, long-lasting masculine fragrance."
  },
  {
    id: '15',
    name: "BLEU DE CHANEL Eau de Parfum Spray",
    price: "13800",
    originalPrice: "13800",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.chanel.com/images//t_one//w_0.51,h_0.51,c_crop/q_auto:good,f_auto,fl_lossy,dpr_1.1/w_620/bleu-de-chanel-eau-de-parfum-spray-3-4fl-oz--packshot-default-107360-9564894232606.jpg",
    buyLink: "https://www.chanel.com/in/fragrance/p/107360/bleu-de-chanel-eau-de-parfum-spray/",
    brand: "Chanel",
    volume: "100ml",
    description: "Iconic fresh aromatic fragrance with woody notes for the modern man."
  },
  {
    id: '16',
    name: "Kaaf by Ahmed AI Maghribi",
    price: "1999",
    originalPrice: "1999",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.ahmedalmaghribi.co.in/wp-content/uploads/2022/03/Kaaf-bottle-768x1024.png",
    buyLink: "https://elixbloom.com/product/ahmed-al-maghribi-kaaf-100ml-edp-men-women/, https://www.ahmedalmaghribi.co.in/shop/extrait-de-parfum/kaaf/",
    brand: "Ahmed AI Maghribi",
    volume: "100ml",
    description: "Arabian fragrance with exotic notes for both men and women."
  },
  {
    id: '17',
    name: "Y Eau de Parfum Intense by Yves Saint Laurent",
    price: "9500",
    originalPrice: "9500",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.fridaycharm.com/cdn/shop/files/ysl34.jpg",
    buyLink: "https://www.fridaycharm.com/products/yves-saint-laurent-y-eau-de-parfum-intense-for-men-2023-release",
    brand: "Yves Saint Laurent",
    volume: "100ml",
    description: "Intense version of the popular Y fragrance with spicy and woody accords."
  },
  {
    id: '18',
    name: "Lattafa Khamrah Qahwa Eau De Parfum Men & Women",
    price: "2849",
    originalPrice: "2849",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.lattafaindia.com/cdn/shop/files/Qahwa.png",
    buyLink: "https://perfumepalace.in/products/lattafa-khamrah-qahwa-eau-de-parfum-100ml-for-men-women, https://elixbloom.com/product/lattafa-khamrah-qahwa-100ml-edp-men-women/",
    brand: "Lattafa",
    volume: "100ml",
    description: "Coffee-infused fragrance with warm spicy notes for men and women."
  },
  {
    id: '19',
    name: "Lattafa Khamrah Eau De Parfum Men & Women",
    price: "2649",
    originalPrice: "2649",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.lattafaindia.com/cdn/shop/files/Khamrah.png",
    buyLink: "https://elixbloom.com/product/lattafa-khamrah-100ml-edp-men-women/, https://www.perfumenetwork.in/products/lattafa-khamrah-eau-de-parfum",
    brand: "Lattafa",
    volume: "100ml",
    description: "Popular oriental fragrance with sweet and spicy notes for both genders."
  },
  {
    id: '20',
    name: "Lattafa Asad Eau de Parfum for Men",
    price: "2089",
    originalPrice: "2089",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.perfumenetwork.in/cdn/shop/products/Asad.png",
    buyLink: "https://elixbloom.com/product/lattafa-asad-perfume-100ml-edp-men-women/, https://www.perfumenetwork.in/products/lattafa-asad-eau-de-parfum-for-men",
    brand: "Lattafa",
    volume: "100ml",
    description: "Masculine fragrance with spicy and woody oriental notes."
  },
  {
    id: '21',
    name: "Afnan 9PM Edp for Men",
    price: "2689",
    originalPrice: "2689",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://elixbloom.com/wp-content/uploads/2025/04/9PM-copy-1-600x600.webp",
    buyLink: "https://elixbloom.com/product/afnan-9pm-100ml-edp-men/, https://fragstalk.in/product/afnan-9pm/",
    brand: "Afnan",
    volume: "100ml",
    description: "Night-time fragrance perfect for evening occasions and special events."
  },
  {
    id: '22',
    name: "Afnan Turathi Blue 90ml Edp for Men And Women",
    price: "2899",
    originalPrice: "2899",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://elixbloom.com/wp-content/uploads/2025/04/Turathi-blue-copy.webp",
    buyLink: "https://elixbloom.com/product/afnan-turathi-blue-90ml-edp-men-and-women/, https://fragstalk.in/product/afnan-turathi/",
    brand: "Afnan",
    volume: "90ml",
    description: "Blue fragrance with fresh aquatic and aromatic notes for both genders."
  },
  {
    id: '23',
    name: "Afnan Modest Une Edp for Men",
    price: "2649",
    originalPrice: "2649",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://elixbloom.com/wp-content/uploads/2025/04/modest-une-.webp",
    buyLink: "https://elixbloom.com/product/afnan-modest-une-100ml-edp-men/",
    brand: "Afnan",
    volume: "100ml",
    description: "Subtle yet distinctive masculine fragrance with elegant character."
  },
  {
    id: '24',
    name: "Blue By Ahmed AI Maghribi",
    price: "1799",
    originalPrice: "1799",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.ahmedalmaghribi.co.in/wp-content/uploads/2024/06/Blue-By-Ahmed1.png",
    buyLink: "https://elixbloom.com/product/ahmed-al-maghribi-blue-by-ahmed-100ml-edp-men-women/, https://www.ahmedalmaghribi.co.in/shop/eau-de-parfum/occidental-fragrance/blue-by-ahmed/",
    brand: "Ahmed AI Maghribi",
    volume: "100ml",
    description: "Fresh blue aquatic fragrance with modern appeal for men and women."
  },
  {
    id: '25',
    name: "Lattafa Pride Nebras Edp for Men & Women",
    price: "2769",
    originalPrice: "2769",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://elixbloom.com/wp-content/uploads/2025/05/Nebras.webp",
    buyLink: "https://elixbloom.com/product/lattafa-nebras-100ml-edp-men-women/, https://fragstalk.in/product/lattafa-pride-nebras/, https://www.perfumenetwork.in/products/lattafa-pride-nebras-eau-de-parfum",
    brand: "Lattafa",
    volume: "100ml",
    description: "Premium pride collection fragrance with luxurious scent profile."
  },
  {
    id: '26',
    name: "Dylan Blue Pour Homme EDT by Versace",
    price: "15600",
    originalPrice: "15600",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.versace.com/dw/image/v2/BGWN_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dwd03204d2/original/90_R721010-R100MLS_RNUL_20_DylanBluePourHommeEDT100ml--Versace-online-store_2_1.jpg",
    buyLink: "https://www.versace.com/in/en/dylan-blue-pour-homme-edt-100-ml/R721010-R100MLS.html",
    brand: "Versace",
    volume: "100ml",
    description: "Fresh aromatic fragrance with aquatic notes and masculine character."
  },
  {
    id: '27',
    name: "Fragrance World French Avenue Liquid Brun Edp for Men",
    price: "2849",
    originalPrice: "2849",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.perfumenetwork.in/cdn/shop/files/1.png",
    buyLink: "https://elixbloom.com/product/fragrance-world-french-avenue-liquid-brun-100ml-edp-men/, https://www.perfumenetwork.in/products/french-avenue-liquid-brun-eau-de-parfum-for-unisex",
    brand: "Fragrance World",
    volume: "100ml",
    description: "French-inspired masculine fragrance with sophisticated brun notes."
  },
  {
    id: '28',
    name: "Afnan Supremacy Not Only Intense Edp",
    price: "3999",
    originalPrice: "3999",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://india.afnan.com/cdn/shop/files/SupremacyIntense-Product-01.jpg",
    buyLink: "https://elixbloom.com/product/afnan-supremacy-not-only-intense-150ml-edp-men/, https://india.afnan.com/products/supremacy-not-only-intense",
    brand: "Afnan",
    volume: "150ml",
    description: "Intense supremacy fragrance with powerful longevity and sillage."
  },
  {
    id: '29',
    name: "Afnan Supremacy Collector's Edition Edp for Men",
    price: "3899",
    originalPrice: "3899",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://india.afnan.com/cdn/shop/files/SupremacyCollectionsEditionFront_Gray.png",
    buyLink: "https://elixbloom.com/product/afnan-supremacy-collectors-edition-100ml-edp-men/, https://india.afnan.com/products/supremacy-collectors-edition",
    brand: "Afnan",
    volume: "100ml",
    description: "Special collector's edition with exclusive fragrance composition."
  },
  {
    id: '30',
    name: "Lattafa Bade'e Al Oud Honor & Glory Edp for Men & Women",
    price: "2349",
    originalPrice: "2349",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.lattafaindia.com/cdn/shop/files/Badee_Al_Oud_Honor_Glory_Bottle.png",
    buyLink: "https://elixbloom.com/product/lattafa-badee-al-oud-honor-glory-100ml-edp-men-women/, https://www.lattafaindia.com/products/badee-al-oud-honor",
    brand: "Lattafa",
    volume: "100ml",
    description: "Oud-based fragrance with honor and glory theme for both genders."
  },
  {
    id: '31',
    name: "Azzaro The Most Wanted Eau de Parfum Intense",
    price: "4750",
    originalPrice: "4750",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://scentoria.co.in/cdn/shop/files/The_Most_Wanted_EDP_Intense_100_ML_Tester.jpg",
    buyLink: "https://scentoria.co.in/products/the-most-wanted-intense-edp, https://sephora.in/product/azzaro-the-most-wanted-eau-de-parfum-intense-spray-v-100ml",
    brand: "Azzaro",
    volume: "50ml",
    description: "Intense version of the popular Most Wanted fragrance with enhanced notes."
  },
  {
    id: '32',
    name: "Lattafa Angham Edp for Men & Women",
    price: "2489",
    originalPrice: "2489",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://www.lattafaindia.com/cdn/shop/files/Angham_Bottle.png",
    buyLink: "https://elixbloom.com/product/lattafa-angham-100ml-edp-men-women/, https://www.lattafaindia.com/products/angham",
    brand: "Lattafa",
    volume: "100ml",
    description: "Versatile fragrance suitable for various occasions for both genders."
  },
  {
    id: '33',
    name: "Emporio Armani Stronger With You Intensely Eau de Parfum for Men",
    price: "8350",
    originalPrice: "8350",
    currentPrice: '',
    priceDate: '2024-01-15',
    image: "https://assets-cf.armani.com/image/upload/f_auto,q_auto:best,ar_4:5,w_1350,c_fill/L8717500_NLP_100ML_F_FW2025.jpg",
    buyLink: "https://www.perfumenetwork.in/products/emporio-armani-stronger-with-you-intensely",
    brand: "Emporio Armani",
    volume: "100ml",
    description: "Intensely passionate fragrance with warm, spicy, and aromatic notes."
  }
];